name: SimplePillars
version: '1.0'
main: me.farmans.simplePillars.SimplePillars
api-version: '1.20'
authors: [Farmans]

commands:
  pstart:
    description: startuje
    usage: /pstart
    permission: op
  pstop:
    description: stopne
    usage: /pstop
    permission: op
  pdistance:
    description: vzdalenost
    usage: /pdistance <distance>
    permission: op
  pheight:
    description: vyška
    usage: /pheight <height>
    permission: op
  pfallmax:
    description: určí počet bloků, při kterým mužou hráči ještě padat, než umřou
    usage: /pfallmax <pocet bloku nez hraci umrou>
    permission: op